import type { Facts } from "@/data/facts";

// Inline tags: <email>…</email> support mailto link, <site>…</site> website link,
// <fatsecret>…</fatsecret> external link.
export default (f: Facts) => ({
  metaTitle: "Terms of Service",
  metaDescription:
    "Read the terms and conditions governing your use of the MyNutriRise app and services.",
  title: "Terms of Service",
  lastUpdated: "Last updated: May 15, 2026",
  // Translations: note that the English version is the legally binding one. Empty in English.
  bindingNote: "",
  sections: [
    {
      heading: "1. Acceptance of Terms",
      blocks: [
        {
          type: "p",
          text: "By downloading, installing, or using MyNutriRise (“the App”), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.",
        },
      ],
    },
    {
      heading: "2. Description of Service",
      blocks: [
        {
          type: "p",
          text: "MyNutriRise is a health and nutrition tracking application that provides:",
        },
        {
          type: "ul",
          items: [
            "Food photo scanning and nutrition analysis",
            "Meal logging and calorie/macro tracking",
            "Intermittent fasting timer and tracking",
            "AI-powered nutrition coaching",
            `Cultural diet database with ${f.DISHES} dishes`,
            "Grocery list generation",
            "Water intake tracking",
            "Body progress tracking with photos",
            "Gamification with badges, XP, and streaks",
            "Health device integration",
          ],
        },
      ],
    },
    {
      heading: "3. Not Medical Advice",
      blocks: [
        {
          type: "p",
          variant: "important",
          text: "IMPORTANT: MyNutriRise is NOT a medical application and does NOT provide medical advice. The information provided is for general educational and informational purposes only.",
        },
        {
          type: "ul",
          items: [
            "Always consult a qualified healthcare professional before making significant changes to your diet or exercise routine.",
            "Do not use this App to diagnose, treat, cure, or prevent any disease.",
            "If you have a medical condition, eating disorder, or are pregnant, consult your doctor before using this App.",
            "AI coaching responses are generated by artificial intelligence and should not replace professional medical advice.",
          ],
        },
      ],
    },
    {
      heading: "4. User Accounts",
      blocks: [
        {
          type: "ul",
          items: [
            "You must provide accurate information when creating an account.",
            "You are responsible for maintaining the security of your account credentials.",
            "You must be at least 13 years old to use this App.",
            "One account per person. Do not share your account.",
          ],
        },
      ],
    },
    {
      heading: "5. Subscription & Payments",
      blocks: [
        {
          type: "ul",
          items: [
            "MyNutriRise offers free and premium subscription tiers.",
            "Premium subscriptions are billed through Google Play Store or Apple App Store.",
            "Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current period.",
            "Refunds are handled according to the respective app store policies.",
            "We reserve the right to change pricing with advance notice.",
          ],
        },
      ],
    },
    {
      heading: "6. Acceptable Use",
      blocks: [
        { type: "p", text: "You agree NOT to:" },
        {
          type: "ul",
          items: [
            "Use the App for any illegal purpose.",
            "Attempt to reverse engineer, hack, or compromise the App.",
            "Use the AI coaching feature for non-health topics.",
            "Upload inappropriate, offensive, or illegal content.",
            "Misrepresent your identity or impersonate others.",
            "Interfere with or disrupt the App's functionality.",
          ],
        },
      ],
    },
    {
      heading: "7. Intellectual Property",
      blocks: [
        {
          type: "ul",
          items: [
            "MyNutriRise, including its design, features, code, and content, is owned by NutriLife and protected by intellectual property laws.",
            "The cultural diet database is proprietary content.",
            "You may not copy, modify, distribute, or create derivative works from the App.",
          ],
        },
      ],
    },
    {
      heading: "8. Third-Party Content",
      blocks: [
        {
          type: "p",
          text: "Nutrition information displayed in this app is provided by FatSecret Platform API and is subject to FatSecret's terms of service available at <fatsecret>https://platform.fatsecret.com</fatsecret>.",
        },
      ],
    },
    {
      heading: "9. User Content",
      blocks: [
        {
          type: "ul",
          items: [
            "You retain ownership of photos and data you upload.",
            "By uploading content, you grant us a limited license to store and process it for providing the service.",
            "We do not claim ownership of your personal health data.",
          ],
        },
      ],
    },
    {
      heading: "10. Limitation of Liability",
      blocks: [
        { type: "p", variant: "caps", text: "To the maximum extent permitted by law:" },
        {
          type: "ul",
          items: [
            "MyNutriRise is provided “AS IS” without warranties of any kind.",
            "We are not liable for any health outcomes resulting from using the App.",
            "We are not liable for data loss, though we take reasonable measures to protect your data.",
            "Our total liability shall not exceed the amount you paid for the App in the last 12 months.",
          ],
        },
      ],
    },
    {
      heading: "11. Termination",
      blocks: [
        {
          type: "ul",
          items: [
            "We may suspend or terminate your account if you violate these Terms.",
            "You may delete your account at any time.",
            "Upon termination, your data will be deleted in accordance with our Privacy Policy.",
          ],
        },
      ],
    },
    {
      heading: "12. Changes to Terms",
      blocks: [
        {
          type: "p",
          text: "We may update these Terms from time to time. Continued use of the App after changes constitutes acceptance of the new Terms.",
        },
      ],
    },
    {
      heading: "13. Contact",
      blocks: [
        { type: "p", text: "For questions about these Terms:" },
        { type: "p", text: "Email: <email>support@mynutririse.com</email>" },
        { type: "p", variant: "tight", text: "Website: <site>https://mynutririse.com</site>" },
      ],
    },
  ],
});
