import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — MyNutriRise",
  description:
    "Read the terms and conditions governing your use of the MyNutriRise app and services.",
};

export default function TermsPage() {
  return (
    <div className="pt-24">
      <article className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-4xl font-bold tracking-tight text-slate-800">
          Terms of Service
        </h1>
        <p className="mt-4 text-sm text-slate-500">
          Last updated: May 15, 2026
        </p>

        <div className="mt-12 space-y-10 text-base leading-7 text-slate-600">
          {/* 1. Acceptance of Terms */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              1. Acceptance of Terms
            </h2>
            <p className="mt-3">
              By downloading, installing, or using MyNutriRise (&ldquo;the
              App&rdquo;), you agree to be bound by these Terms of Service. If
              you do not agree, do not use the App.
            </p>
          </section>

          {/* 2. Description of Service */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              2. Description of Service
            </h2>
            <p className="mt-3">
              MyNutriRise is a health and nutrition tracking application that
              provides:
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Food photo scanning and nutrition analysis</li>
              <li>Meal logging and calorie/macro tracking</li>
              <li>Intermittent fasting timer and tracking</li>
              <li>AI-powered nutrition coaching</li>
              <li>Cultural diet database with 1200+ dishes</li>
              <li>Grocery list generation</li>
              <li>Water intake tracking</li>
              <li>Body progress tracking with photos</li>
              <li>Gamification with badges, XP, and streaks</li>
              <li>Health device integration</li>
            </ul>
          </section>

          {/* 3. Not Medical Advice */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              3. Not Medical Advice
            </h2>
            <p className="mt-3 font-semibold text-slate-800">
              IMPORTANT: MyNutriRise is NOT a medical application and does NOT
              provide medical advice. The information provided is for general
              educational and informational purposes only.
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                Always consult a qualified healthcare professional before making
                significant changes to your diet or exercise routine.
              </li>
              <li>
                Do not use this App to diagnose, treat, cure, or prevent any
                disease.
              </li>
              <li>
                If you have a medical condition, eating disorder, or are
                pregnant, consult your doctor before using this App.
              </li>
              <li>
                AI coaching responses are generated by artificial intelligence
                and should not replace professional medical advice.
              </li>
            </ul>
          </section>

          {/* 4. User Accounts */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              4. User Accounts
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                You must provide accurate information when creating an account.
              </li>
              <li>
                You are responsible for maintaining the security of your account
                credentials.
              </li>
              <li>You must be at least 13 years old to use this App.</li>
              <li>One account per person. Do not share your account.</li>
            </ul>
          </section>

          {/* 5. Subscription & Payments */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              5. Subscription &amp; Payments
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                MyNutriRise offers free and premium subscription tiers.
              </li>
              <li>
                Premium subscriptions are billed through Google Play Store or
                Apple App Store.
              </li>
              <li>
                Subscriptions auto-renew unless cancelled at least 24 hours
                before the end of the current period.
              </li>
              <li>
                Refunds are handled according to the respective app store
                policies.
              </li>
              <li>
                We reserve the right to change pricing with advance notice.
              </li>
            </ul>
          </section>

          {/* 6. Acceptable Use */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              6. Acceptable Use
            </h2>
            <p className="mt-3">You agree NOT to:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Use the App for any illegal purpose.</li>
              <li>
                Attempt to reverse engineer, hack, or compromise the App.
              </li>
              <li>Use the AI coaching feature for non-health topics.</li>
              <li>Upload inappropriate, offensive, or illegal content.</li>
              <li>Misrepresent your identity or impersonate others.</li>
              <li>
                Interfere with or disrupt the App&apos;s functionality.
              </li>
            </ul>
          </section>

          {/* 7. Intellectual Property */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              7. Intellectual Property
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                MyNutriRise, including its design, features, code, and content,
                is owned by NutriLife and protected by intellectual property
                laws.
              </li>
              <li>The cultural diet database is proprietary content.</li>
              <li>
                You may not copy, modify, distribute, or create derivative works
                from the App.
              </li>
            </ul>
          </section>

          {/* 8. Third-Party Content */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              8. Third-Party Content
            </h2>
            <p className="mt-3">
              Nutrition information displayed in this app is provided by
              FatSecret Platform API and is subject to FatSecret&apos;s terms of
              service available at{" "}
              <a
                href="https://platform.fatsecret.com"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-emerald-600 underline underline-offset-4 hover:text-emerald-700"
              >
                https://platform.fatsecret.com
              </a>
              .
            </p>
          </section>

          {/* 9. User Content */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              9. User Content
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>You retain ownership of photos and data you upload.</li>
              <li>
                By uploading content, you grant us a limited license to store
                and process it for providing the service.
              </li>
              <li>
                We do not claim ownership of your personal health data.
              </li>
            </ul>
          </section>

          {/* 10. Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              10. Limitation of Liability
            </h2>
            <p className="mt-3 text-xs font-semibold uppercase tracking-wide text-slate-500">
              To the maximum extent permitted by law:
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                MyNutriRise is provided &ldquo;AS IS&rdquo; without warranties
                of any kind.
              </li>
              <li>
                We are not liable for any health outcomes resulting from using
                the App.
              </li>
              <li>
                We are not liable for data loss, though we take reasonable
                measures to protect your data.
              </li>
              <li>
                Our total liability shall not exceed the amount you paid for the
                App in the last 12 months.
              </li>
            </ul>
          </section>

          {/* 11. Termination */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              11. Termination
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                We may suspend or terminate your account if you violate these
                Terms.
              </li>
              <li>You may delete your account at any time.</li>
              <li>
                Upon termination, your data will be deleted in accordance with
                our Privacy Policy.
              </li>
            </ul>
          </section>

          {/* 12. Changes to Terms */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              12. Changes to Terms
            </h2>
            <p className="mt-3">
              We may update these Terms from time to time. Continued use of the
              App after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          {/* 13. Contact */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800">
              13. Contact
            </h2>
            <p className="mt-3">For questions about these Terms:</p>
            <p className="mt-3">
              Email:{" "}
              <a
                href="mailto:support@mynutririse.com"
                className="font-medium text-emerald-600 underline underline-offset-4 hover:text-emerald-700"
              >
                support@mynutririse.com
              </a>
            </p>
            <p className="mt-1">
              Website:{" "}
              <a
                href="https://mynutririse.com"
                className="font-medium text-emerald-600 underline underline-offset-4 hover:text-emerald-700"
              >
                https://mynutririse.com
              </a>
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}
